### ISSUE TITLE
AttributeError: 'Track' object has no attribute 'alternative_list'

### ISSUE THREAD

**Issue by Footsiefat** [kokarare1212/librespot-python#52]
On playing a specific track ([https://open.spotify.com/track/1peqrZv4XESUQ0oG4bWU7t](https://open.spotify.com/track/1peqrZv4XESUQ0oG4bWU7t)) librespot crashes for some reason with the following backtrace...

![image](https://user-images.githubusercontent.com/12180913/124738789-642c8280-df6d-11eb-8b2f-e83f726bb501.png)

**Comment by kokarare1212** [comment]
Thank you for your inquiry.
That error itself was fixed with
https://github.com/kokarare1212/librespot-python/commit/e8f0e024d97fc6b96533dfdff841ab76bb6cc5cf#diff-e4428e91397831443749277947bf7fad32834e3b2869b3e02405f503b7d0d689

However, in my environment, it seems to be failing to load packets, so I will investigate additionally.

**Comment by Footsiefat** [comment]
Thanks for the quick reply and patch, although this doesn't seem to be fixing the main problem for me, as I still get the same error.
![image](https://user-images.githubusercontent.com/12180913/124849795-879a1080-dff3-11eb-8dea-c4e82a672833.png)

**Comment by kokarare1212** [comment]
It was a mistake.
This commit should resolve the error itself.
https://github.com/kokarare1212/librespot-python/commit/e9c396b756db42ef9d2d0716fb314e24f3389324

**Comment by Footsiefat** [comment]
It seemed to fix that error!

Although there is a new error now in its place:

![image](https://user-images.githubusercontent.com/12180913/124856788-4576cc00-dfff-11eb-9a2d-ee6f709998bd.png)

**Comment by Footsiefat** [comment]
I also found something interesting!

Turns out for one of the tracks that can cause librespot to crash. I managed to find/get to different url's for the exact same song, one of these urls works with librespot and the other causes the crash. Here they are if you wanna have a look for testing! :)

WORKING: [https://open.spotify.com/track/2CgOd0Lj5MuvOqzqdaAXtS](https://open.spotify.com/track/2CgOd0Lj5MuvOqzqdaAXtS)
BROKEN: [https://open.spotify.com/track/3ISYGHoYnu4gos6JNMfL4z](https://open.spotify.com/track/3ISYGHoYnu4gos6JNMfL4z)

**Comment by kokarare1212** [comment]
Yes, perhaps the broken track is failing to load packets looking for a replacement because the original track is not available.
I may be slow on bug tracking because I can't find the time.

**Comment by Footsiefat** [comment]
Yeah maybe. 👍 I'm great at python so I might be able to help debug this when I get time, although I wasn't the one who wrote this so I'll see how I go

**Comment by Footsiefat** [comment]
Interesting find, if you do an api request on a specific track that breaks, the "id" it returns in the json will actually be different, if you try to play that new track id it all play  perfectly with no problems. Idk if this can help you fix the bug but you're welcome lol

**Comment by kokarare1212** [comment]
It was a bug in migrating the original data when using the Metadata.Track alternative.

**Comment by kokarare1212** [comment]
I've fixed it and will close the issue.
